version: "3.5"

services:
    app:
        image: "node:20-alpine"
        container_name: "app"
        command: "./src/server.js"
        working_dir: "/app"
        volumes:
            - .:/app
        ports:
            - ${APP_PORT:-3001}:3001
