version: "3.5"

services:
    app:
        image: "node:20-alpine"
        entrypoint: "./docker/entrypoint.sh"
        command: "./src/server.ts"
        working_dir: "/app"
        environment:
            - NODE_ENV=${APP_ENV:-production}
            - NODE_CONFIG_DIR=./src/config
        volumes:
            - .:/app
        ports:
            - ${APP_PORT:-3001}:3001
