app:
  name: Caching http microservice

  port: 3001

  routes:
    - route: /getCachedResult
      proxy: http://localhost:3002/mocks/getSlow
      cache: 60000 # s
      timeout: 500 # ms
      retries: 3
      factor: 2

    - route: /getUnionResult
      union:
        user: http://localhost:3002/mocks/getSlow
        post: http://localhost:3002/mocks/getFast
      cache: 3600 # s
      timeout: 500 # ms
      retry: 3
      factor: 2

    - route: /getFirstResult
      first:
        - http://localhost:3002/mocks/getTimeout
        - http://localhost:3002/mocks/getFast
      cache: 3600 # s
      timeout: 500 # ms
      retry: 3
      factor: 2

mock:
  port: 3002
